# Generated by Django 4.1.3 on 2022-11-22 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "business_name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Business Name"
                    ),
                ),
                (
                    "caption",
                    models.CharField(max_length=255, verbose_name="Business Caption"),
                ),
                ("contact", models.CharField(max_length=50, verbose_name="Contact")),
                ("email", models.EmailField(max_length=254)),
                ("profile", models.ImageField(upload_to="")),
            ],
        ),
    ]
